language: php

sudo: false

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1

install:
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls

notifications:
  email:
    on_success: never
    on_failure: change