language: php

php:
  - 7.0
  - 7.1

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - setup=basic
    - COMPOSER_DISCARD_CHANGES=true
    - COMPOSER_NO_INTERACTION=1
    - COMPOSER_DISABLE_XDEBUG_WARN=1

install: travis_retry composer install --prefer-dist

script: vendor/bin/phpunit

notifications:
  email:
    on_success: never
    on_failure: change